AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Car Ping Hub

# Parameters:
#   ProjectId:
#     Type: String
#     Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  APIGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Policies:
        - VPCAccessPolicy: {}
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SubnetIds:
          - subnet-a22129c5
        SecurityGroupIds:
          - sg-41bdf839
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

  # Api:
  #   Type: AWS::ApiGateway::RestApi
  #   Properties:
  #     Name: MyAPI
  #     DefinitionUri: swagger.yaml
  #     StageName: Prod
  #     Variables:
  #         LambdaFunctionName: !Ref LambdaFunction
